CREATE TABLE cliente (
    cod_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nme_cliente VARCHAR(255) NOT NULL,
    dta_nascimento DATE,
    nro_cpf VARCHAR(11) NOT NULL UNIQUE,
    dta_criacao TIMESTAMP NOT NULL
);

CREATE INDEX idx_cliente_cpf ON cliente(nro_cpf);
CREATE INDEX idx_cliente_nome ON cliente(nme_cliente);
CREATE INDEX idx_cliente_data_nascimento ON cliente(dta_nascimento);
CREATE INDEX idx_cliente_data_criacao ON cliente(dta_criacao);