CREATE TABLE endereco (
    cod_endereco BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nme_logradouro VARCHAR(255) NOT NULL,
    nme_bairro VARCHAR(255) NOT NULL,
    nro_cep VARCHAR(8) NOT NULL,
    nme_cidade VARCHAR(255) NOT NULL,
    nme_estado VARCHAR(2) NOT NULL
);

CREATE INDEX idx_endereco_cidade ON endereco(nme_cidade);
CREATE INDEX idx_endereco_nome_bairro ON endereco(nme_bairro);
CREATE INDEX idx_endereco_nome_estado ON endereco(nme_estado);
CREATE INDEX idx_endereco_nro_cep ON endereco(nro_cep);