CREATE TABLE ocorrencia (
   cod_ocorrencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   cod_cliente BIGINT NOT NULL,
   cod_endereco BIGINT NOT NULL,
   dta_ocorrencia TIMESTAMP NOT NULL,
   sta_ocorrencia VARCHAR(20) NOT NULL,

   CONSTRAINT fk_ocorrencia_cliente
       FOREIGN KEY (cod_cliente) REFERENCES cliente(cod_cliente),
   CONSTRAINT fk_ocorrencia_endereco
       FOREIGN KEY (cod_endereco) REFERENCES endereco(cod_endereco)
);

CREATE INDEX idx_ocorrencia_data_ocorrencia ON ocorrencia(dta_ocorrencia);
CREATE INDEX idx_ocorrencia_sta_ocorrencia ON ocorrencia(sta_ocorrencia);
CREATE INDEX idx_ocorrencia_cod_cliente ON ocorrencia(cod_cliente);
CREATE INDEX idx_ocorrencia_cod_endereco ON ocorrencia(cod_endereco);