CREATE TABLE foto_ocorrencia (
   cod_foto_ocorrencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   cod_ocorrencia BIGINT NOT NULL,
   dta_criacao TIMESTAMP NOT NULL,
   dsc_path_bucket VARCHAR(500) NOT NULL,
   dsc_hash VARCHAR(255) NOT NULL,

   CONSTRAINT fk_foto_ocorrencia FOREIGN KEY (cod_ocorrencia) REFERENCES ocorrencia(cod_ocorrencia)
);

CREATE INDEX idx_foto_ocorrencia_dta_criacao ON foto_ocorrencia(dta_criacao);
CREATE INDEX idx_foto_ocorrencia_dsc_path_bucket ON foto_ocorrencia(dsc_path_bucket);
CREATE INDEX idx_foto_ocorrencia_dsc_hash ON foto_ocorrencia(dsc_hash);
CREATE INDEX idx_foto_ocorrencia_cod_ocorrencia ON foto_ocorrencia(cod_ocorrencia);